export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const ON_CLOSE_FLOATING_CART = 'ON_CLOSE_FLOATING_CART';
export const ON_INCREASE_QUANTITY = 'ON_INCREASE_QUANTITY';
export const ON_DECREASE_QUANTITY = 'ON_DECREASE_QUANTITY';